### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by dsyer**
I had to make some changes so the project will build. I also switched to Java 8, but it doesn't make it any faster or slower for me. The `@WebMvcTest` starts in <2sec for me (on my slow laptop).

### CODE REVIEW

**Comment by phauer** [comment]
Thank you very much! I'm so sorry for the poor example (copy & paste mistake).

That's interesting. It still takes 3 seconds on my notebook. And it also doesn't matter if I execute the test via IntelliJ or via `mvn clean test`.

```
2019-03-24 12:34:02.413  INFO 18123 --- [           main] com.example.demo.TestControllerTest      : Started TestControllerTest in 2.959 seconds (JVM running for 4.136)
```

Same on JRE 8 and 11.

Maybe my notebook is just slow? 

I can bring the time down to 2.3 seconds by adding `-noverify -XX:TieredStopAtLevel=1`. Have you also done that?

However, the outlook to Spring Boot 2.2's lazy loading is really promising!

**Comment by dsyer** [comment]
Yes, I have `-noverify -XX:TieredStopAtLevel=1` (can't think of a reason not to do that, especially for dev time). Spring Boot 2.2 will make a big difference because (for example) you won't need to create the security layer. I'm still surprised it takes more than a second to start though, so I'll have a closer look.

**Comment by dsyer** [comment]
The JDK version will make a difference too (the latest OpenJDK releases are slow for JDK 8 and 11). I have 8u152.

**Comment by phauer** [comment]
Good point. But I have the same performance on 11.0.2-open, 8.0.202-zulu and 8.0.201-oracle.

Yes, the options `-noverify -XX:TieredStopAtLevel=1` should always be set during dev time. I'll add them to the templates of the JUnit run configs in IntelliJ. In our real app, I can bring the time down from 5.4 to 3.5 seconds, which is pretty good.

Again, thank you very much for digging deeper! That's great.

**Comment by mgunter-pivotal** [comment]
Curious if this (http://blog.dmitryalexandrov.net/quarkus-blast-from-the-future/ )  approach would help at all?
....results posted: "WildFly ~49 seconds start-up, Native ~2 seconds start-up time;"

here's another blog (https://brunobat.com/2019/03/12/tomee-vs-spring-boot-vs-quarkus/)
...."startup time for springboot ~7 secs to under 1 sec"

**Comment by dsyer** [comment]
11.0.2 and 8.0.201 were the ones with the startup regression IIRC. Not sure if Zulu 202 is different, but you should definitely try older builds 11.0.1 and 8u152 if you can still track them down.

**Pull request merged**
